import "./globals.css";
import Header from "@/components/Header";


export const metadata = {
  title: "Cat API",
  description: "Generated by cat api",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-pink-100">
        <header>
          <Header />
        </header>
        {children}
      </body>
    </html>
  );
}
