import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { sourGummy } from "@/app/font";


export const metadata = {
  title: "Cat API",
  description: "Generated by cat api",
  icons :    {
    icon: "/favicon.ico"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sourGummy.className} bg-tulipe`}>
        <header>
          <Header />
        </header>
        <main>
            {children}
        </main>
        <footer className="relative z-50 w-screen h-25 bg-fuchsia-800 text-white box-shadow-lg shadow-[0_-10px_15px_rgba(150,50,200,0.5)] ">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
