import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { sourGummy } from "@/app/font";


export const metadata = {
  title: "Cat API",
  description: "Generated by cat api",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${sourGummy.className} bg-pink-100`}>
        <header>
          <Header />
        </header>
        <main>
            {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
